### ISSUE TITLE
Why tags uppercase?

### ISSUE THREAD

**Issue by voronianski** [watilde/jsss-compiler#43]
```javascript
tags.H1.color = 'red'; // why not `tags.h1` ?
```

**Comment by watilde** [comment]
@voronianski Hello! Just beacause original spec used uppercase. refs: http://www.w3.org/Submission/1996/1/WD-jsss-960822

**Comment by voronianski** [comment]
@watilde IMHO generated CSS with uppercase tags looks ugly.

**Comment by watilde** [comment]
I read some example on w3c, there was both case. So we should make it be able to select it :)

Well, I founded a bug:
```
$ cat style.js
tags.H1.color = 'red';
tags.h1.color = 'blue';

$ jsss
H1 {
  color: red;
}

h1 {
  color: blue;
}
```

I'll change this to
```
$ cat style.js
tags.H1.color = 'red';
tags.h1.color = 'blue';

$ jsss
h1 {
  color: blue;
}
```

**Comment by voronianski** [comment]
@watilde :+1:

**Comment by watilde** [comment]
Closing in favor of #44. Thanks!
